server:
  port: 8700
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test_route
          uri:  http://localhost:9200/
          predicates:
            - Path=/api/common/**
        - id: test_route
            uri:  http://localhost:9100/
            predicates:
              - Path= /api/test/**
